# Site settings
title: Polymérisation des concepts
email: alexandre, point, ignjatovic, arobase, gmail, point, com
description: "Les réflexions d'un rubyiste heureux..."
baseurl: ""
username: bankair
url: "http://polymerisation-des-concepts.fr"

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['Gemfile', 'Gemfile.lock', 'pull_and_build.sh', 'push_to_prod.sh']
