# Site settings
title: Polymérisation des concepts
email: alexandre.ignjatovic@gmail.com
description: "Les réflexions d'un rubyiste heureux..."
baseurl: ""
username: bankair
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: Rouge
